### ISSUE TITLE
Add my profile Nikshep A Kulli

### ISSUE THREAD

**Issue by nikshepkulli** [connectleadme/StartupWebsite#11]
https://github.com/connectleadme/StartupWebsite/blob/2fe5a0e1c8a8c45744f83a902db4bcbeba4ce75b/src/components/TeamsInfo.tsx#L9

 name: "Nikshep A Kulli",
    path: nikshepkulli,
    about: "CTO|Data Educator | Nurturing Minds in Data Structures, Text Analysis, MongoDB, and Data Science Architecture 🚀💻 | Passionate about Empowering Future Tech Leaders",
    links: [
      {
        link: "https://www.instagram.com/name_is_niku/",
        icon: instaicon,
      },
      {
        link: "nikshepkulli9@gmail.com",
        icon: mailicon,
      },
      {
        link: "https://www.linkedin.com/in/nikshepkulli/",
        icon: linkedinicon,
      },
      {
        link: "https://github.com/nikshepkulli",
        icon: githubicon,
      },
    ],
  },
![USCIS_photo](https://github.com/connectleadme/StartupWebsite/assets/48430792/9e2677cb-1978-4002-82b4-907060c5a92c)

**Comment by rohithandanala** [comment]
Added
