### ISSUE TITLE
Michael info

### ISSUE THREAD

**Issue by Mianja23** [connectleadme/StartupWebsite#13]
name: "Michael Berlingo",
path: michaelBerlingo,
about: "Founder & CEO | Passionate Entrepreneur | Management Graduate from Sacred Heart University",
links: [
{
link: "https://www.instagram.com/name_is_niku/",
icon: instaicon,
},
{
link: "[mvberlingo@gmail.com](mailto:mvberlingo@gmail.com)",
icon: mailicon,
},
{
link: "https://www.linkedin.com/in/mblingo/",
icon: linkedinicon,
}
],
},

**Comment by rohithandanala** [comment]
Added
