### ISSUE TITLE
Changes to home page

### ISSUE THREAD

**Issue by Mianja23** [connectleadme/StartupWebsite#17]
![image (29)](https://github.com/connectleadme/StartupWebsite/assets/154771869/99345569-7717-4c1c-96ba-f35513d4e413)

Change to "Leadme"
"Don’t Just Follow the crowd, Lead it.”

For "Our Vision" section put this information under it 
Mission Statement: At Leadme, our mission is to empower the aspirations of students by providing a dynamic and inclusive platform for discovering entry level and minimum-wage job opportunities. We are dedicated to fostering a supportive community that bridges the gap between students and employers, facilitating skill development, and igniting the path towards meaningful career journeys. Leadme is committed to innovation, affordability, and collaboration, ensuring that every student can confidently navigate their way to valuable work experiences year round.
Vision: Leadme envisions a world where every student has access to diverse job opportunities, gaining essential work experience and building a foundation for their future careers. We aspire to be the go-to Student Employment Hub, continually innovating and expanding our offerings to enhance the job-seeking journey for both students and employers.

**Comment by rohithandanala** [comment]
Done
