### ISSUE TITLE
Anthony Ivanov

### ISSUE THREAD

**Issue by Anton10169** [connectleadme/StartupWebsite#18]
{
    name: "#Anthony Ivanov",
    path: , // Send image technical team for uploading
    about: "CFO | Experienced Young Entrepreneur",
    links: [
      {
        link: "your scocial media link",
        icon: instaicon, // leave this icon for technical team
      },
      {
        link: "anthonyivanov00@gmail.com",
        icon: mailicon, // leave this icon for technical team
      },
      {
        link: "www.linkedin.com/in/anthony-ivanov

",
        icon: linkedinicon, // leave this icon for technical team
      }, // Add new link if you have any more profiles
    ],
  },

**Comment by rohithandanala** [comment]
Added
