### ISSUE TITLE
Rushi Solanke

### ISSUE THREAD

**Issue by rishisolanke** [connectleadme/StartupWebsite#21]
{
    name: "Rushikesh Balkrushna Solanke",
    path: rohithimg, // Send image technical team for uploading
    about: "Marketing Manager | Computer Science Grad at Sacred Heart University
![IMG_0931](https://github.com/connectleadme/StartupWebsite/assets/60250678/9ba8acaa-f45b-4988-86dc-127d2892b2b1)
",
    links: [
      {
        link: "https://www.instagram.com/rushi.solanke57/",
        icon: instaicon, // leave this icon for technical team
      },
      {
        link: "https://mail.google.com/rishisolanke57@gmail.com",
        icon: mailicon, // leave this icon for technical team
      },
      {
        link: "https://www.linkedin.com/in/rushikesh-balkrushna-solanke-99546b163/",
        icon: linkedinicon, // leave this icon for technical team
      }, // Add new link if you have any more profiles
    ],
  },

**Comment by rohithandanala** [comment]
Added
