### ISSUE TITLE
Ujwal Geed

### ISSUE THREAD

**Issue by Ujwalgeed** [connectleadme/StartupWebsite#23]
{
    name: "Ujwal Geed",
    path: rohithimg, // Send image technical team for uploading
    about: "Sales Officer | Grad Business Analytics Student @ Sacred Heart University",
    links: [
      {
        link: "https://www.instagram.com/ujwalgeed/",
        icon: instaicon, // leave this icon for technical team
      },
      {
        link: "Ujjwalgeed@gmail.com",
        icon: mailicon, // leave this icon for technical team
      },
      {
        link: "https://www.linkedin.com/in/ujwal-geed-8a0063218/",
        icon: linkedinicon, // leave this icon for technical team
      }, // Add new link if you have any more profiles
    ],
  },

**Comment by rohithandanala** [comment]
Added
